InstHub/Controllers/ConferencesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InstHub.Controllers
{
    public class ConferencesController : Controller
    {
        public IActionResult UserConference()
        {
            return View();
        }

        public IActionResult UserConferences()
        {
            return View();
        }
    }
}

InstHub/Views/Conferences/UserConference.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Совещание 21.06";
}

<div class="conference_main">
    <div class="conference_video">
        <div class="conference_caption">
            <h4 style="color:white">Совещание 21.06</h4>
        </div>
        <div class="main_video_section">
            <div class="video_section">
                <h3 style="color:white">Данное cовещание запланировано на 21.06</h3>
            </div>
            <div class="under_video_section">
                <button class="icon_button" disabled>
                    <img src="/images/conference/camera_icon.png" alt="Камера">
                </button>
                <button class="icon_button" disabled>
                    <img src="/images/conference/microphone_icon.png" alt="Микрофон">
                </button>
            </div>
        </div>
    </div>
    <div class="conference_chat">
        <div class="chat_caption">
            <h4>Чат</h4>
        </div>
        <div class="chat_history">
        </div>
        <div class="chat_input">
            <input type="text" name="name" value="" disabled/>
        </div>
    </div>
</div>

InstHub/Views/Conferences/UserConferences.cshtml
@using InstHub.Data.Identity
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppIdentityUser> SignInManager
@inject UserManager<AppIdentityUser> UserManager
@{
    ViewData["Title"] = "Конференции";
}

<div class="">
    <h3>Конференции пользователя @User.Identity?.Name!</h3>

    <div class="confs_div">
        <div class="el_line">
            <a asp-controller="Conferences" asp-action="UserConference" class="a_bt_add">
                <div class="bg_file_add">
                    <img src="/images/conference_ico.png" class="file_ico_class" />
                </div>
                <p>Совещание 21.06</p>
            </a>
        </div>
    </div>
</div>